sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
- npm install -g mupx

- openssl aes-256-cbc -K $encrypted_b30ee50bb6d2_key -iv $encrypted_b30ee50bb6d2_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
services: mongodb
script:
- meteor --test --settings dev-settings.json --release velocity:METEOR@1.1.0.2_3
after_success:
- ./deploy.sh
