sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_b30ee50bb6d2_key -iv $encrypted_b30ee50bb6d2_iv
  -in settings.json.enc -out settings.json -d
- curl https://install.meteor.com/ | sh
- npm install -g mupx
- openssl aes-256-cbc -K $encrypted_b30ee50bb6d2_key -iv $encrypted_b30ee50bb6d2_iv
  -in mup.json.enc -out mup.json -d
- openssl aes-256-cbc -K $encrypted_b30ee50bb6d2_key -iv $encrypted_b30ee50bb6d2_iv
  -in digital_ocean.enc -out /Users/mikecho/.ssh/digital_ocean -d
services: mongodb
script:
- meteor --test --settings dev-settings.json --release velocity:METEOR@1.1.0.2_3
after_success:
- mupx deploy
